### ISSUE TITLE
Netplan config section contains critical information

### ISSUE THREAD

**Issue by danielr0815** [UbuntuForums/wireless-info#16]
By using Ubuntu 24.04 the script creates critical infos which conains also the wifi password. I had to replace the password manually by ******
```
##### NetworkManager profiles ###########

##### Netplan config ####################

[/etc/netplan/01-network-manager-all.yaml]
network:
  version: 2
  renderer: NetworkManager

[/etc/netplan/50-cloud-init.yaml]
network:
    ethernets:
        enx843a5b2bc7f3:
            dhcp4: true
    version: 2
    wifis: {}

[/etc/netplan/90-NM-94104522-29f2-4254-8c06-7c03988b7b85.yaml]
network:
  version: 2
  wifis:
    NM-94104522-29f2-4254-8c06-7c03988b7b85:
      renderer: NetworkManager
      match:
        name: "wlo1"
      dhcp4: true
      dhcp6: true
      access-points:
        "LOUNGE":
          auth:
            key-management: "psk"
            password: "************"
          networkmanager:
            uuid: "94104522-29f2-4254-8c06-7c03988b7b85"
            name: "LOUNGE"
            passthrough:
              wifi-security.auth-alg: "open"
              ipv6.addr-gen-mode: "default"
              ipv6.ip6-privacy: "-1"
              proxy._: ""
      networkmanager:
        uuid: "94104522-29f2-4254-8c06-7c03988b7b85"
        name: "LOUNGE"
```
